name: Smart Contracts CI

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  hardhat:
    strategy:
      fail-fast: true

    name: Hardhat project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
          cache-dependency-path: "contracts/yarn.lock"

      - name: Install Node dependencies
        run: |
          yarn install

      - name: Run Hardhat tests
        run: |
          yarn test
        id: hardhat-test
